Update examples and add helm charts
wescale/microservices-demo pull request #2
Opened 2024-01-02 15:31 UTC by alphayax

2024-01-05 10:23 UTC, mathieulaude commented on .idea/.gitignore
Selon moi il faudrait ignorer tout le répertoire .idea à la racine du repo

2024-01-05 10:24 UTC, mathieulaude requested changes

2024-01-05 10:24 UTC, mathieulaude commented on .helm/demo-microservices/charts/mongodb-14.4.3.tgz
Pourquoi l'ajouter ici et pas simplement pointer sur la version en ligne du package ?

2024-01-08 08:28 UTC, alphayax commented on .helm/demo-microservices/charts/mongodb-14.4.3.tgz
La version en ligne est déja indiqué dans le chart.json. 
Il a été rajouté automatiquement avec le helm dependency upgrade (ce qui permet d'avoir un chart de base complet pret a etre déployé). J'ai pour habitude de l'intégré dans le repo, mais si tu penses que c'est superflux je peux le retirer.

2024-01-29 14:13 UTC, merged